android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/tech/threefold/mycelium/MainActivity.kt
ios/Runner.xcodeproj/xcshareddata/xcschemes/MyceliumTunnel.xcscheme
lib/main.dart
pubspec.lock
pubspec.yaml

from com.example.myceliumflut to tech.threefold.mycelium

change package name.

---

ios/MyceliumTunnel/PacketTunnelProvider.swift
ios/Runner/AppDelegate.swift
ios/mycelios/Cargo.lock
ios/mycelios/Cargo.toml
ios/mycelios/src/lib.rs
lib/main.dart
rust/Cargo.lock
rust/Cargo.toml

- properly pass secretKey and peers from flutter to Swift
-  refactor ios createTunnel func

Proper ios

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/tech/threefold/mycelium/MainActivity.kt
android/app/src/main/kotlin/tech/threefold/mycelium/TunService.kt
ios/MyceliumTunnel/PacketTunnelProvider.swift
ios/Podfile.lock
lib/main.dart
pubspec.lock
pubspec.yaml

chore(tun_flutter): remove tun_flutter plugin.

---

android/app/src/main/kotlin/tech/threefold/mycelium/MainActivity.kt
android/app/src/main/kotlin/tech/threefold/mycelium/TunService.kt
android/gradle.properties

- use CoroutineScope instead of GlobalScope to launch mycelium
- proper onDestroy handler

feat(android): proper onDestroy()

---

android/app/src/main/kotlin/tech/threefold/mycelium/MainActivity.kt
android/app/src/main/kotlin/tech/threefold/mycelium/TunService.kt

it was deleted because of the linter warning

fix(android): put back the code to ask for VPN permission.

---

android/app/build.gradle
android/app/proguard-rules.pro
pubspec.yaml

The crashed caused by proguard, minfiy, and shrink process
fixes #26

fix(android): fix crashed android release APK.

---

ios/Runner/AppDelegate.swift
mycelmob/Cargo.lock
mycelmob/Cargo.toml

Very first run will always failed because the tunnel started before the tunnel provider really created.
The trick (from developer forum) is to retry the process.

fix(ios): proper very first run.

---

ios/MyceliumTunnel/PacketTunnelProvider.swift
ios/Runner/AppDelegate.swift
mycelmob/Cargo.lock
mycelmob/Cargo.toml

- simple handler to prevent `stop` to stuck when mycelium failed
- refactor unchanged variables to const
- add some comments
Proper handling issue is tracked at
https://github.com/threefoldtech/myceliumflut/issues/35

fix(ios): simple mycelium failure handler.

---

lib/main.dart
mycelmob/Cargo.lock
mycelmob/Cargo.toml

Peers textfield improvement

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/tech/threefold/mycelium/MainActivity.kt
android/app/src/main/kotlin/tech/threefold/mycelium/NetworkStateCallback.kt
android/app/src/main/kotlin/tech/threefold/mycelium/TunService.kt

only in monitoring mode
part of #40

feat(android): add NetworkCallback.

---

ios/MyceliumTunnel/PacketTunnelProvider.swift
ios/Runner/AppDelegate.swift
lib/main.dart

feat(ios): tunnel status monitoring and handling

---

ios/Runner/AppDelegate.swift

fix(ios): very first run regression fix.

---

.github/workflows/macos_build.yml
macos/MyceliumTunnel/PacketTunnelProvider.h
macos/Runner.xcodeproj/project.pbxproj
macos/Runner/Configs/AppInfo.xcconfig
macos/Runner/MainFlutterWindow.swift
mycelmob/Cargo.lock
mycelmob/Cargo.toml

feat(macos build): macos github actions and cleanup

---

README.md

readme update for windows and macos

---

lib/main.dart
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

fix(windows): add close handler.

---

ios/MyceliumTunnel/PacketTunnelProvider.h
mycelffi/Cargo.lock
mycelffi/Cargo.toml
mycelmob/Cargo.lock
mycelmob/Cargo.toml

chore(mycelium): update mycelium to the latest release

---

macos/Runner.xcodeproj/project.pbxproj
macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
macos/Runner/Configs/AppInfo.xcconfig
pubspec.yaml

from myceliumflut to mycelium-network

change macos display name

---

macos/MyceliumTunnel/MyceliumTunnel.entitlements
macos/Runner.xcodeproj/project.pbxproj
macos/Runner/DebugProfile.entitlements
macos/Runner/Release.entitlements
pubspec.yaml

remove `com.apple.security.network.server` entitlement
fixes #103

fix(macos): remove unused entitlement

---

android/app/src/main/kotlin/tech/threefold/mycelium/MainActivity.kt

fix(android): Android 34 need explicit android:exported

---

.github/workflows/android_build.yml
.github/workflows/android_release.yml
.github/workflows/ios_build.yml
.github/workflows/macos_build.yml
.github/workflows/windows_build.yaml
ios/Podfile.lock
ios/Runner/AppDelegate.swift
macos/Podfile.lock
macos/Runner/AppDelegate.swift
pubspec.lock
pubspec.yaml

flutter: upgrade SDK

---

android/app/src/main/kotlin/tech/threefold/mycelium/rust/uniffi/mycelmob/mycelmob.kt
mycelmob/Cargo.lock
mycelmob/Cargo.toml

Upgrade `uniffi` and mycelium

---

macos/Runner.xcodeproj/project.pbxproj
macos/Runner/RunnerDebug.entitlements

Needed by vscode flutter extension during development.

fix(macos): re-enable `incoming connection server` capabilites in debug mode.

---

lib/main.dart

- remove empty entries
- remove duplicated entries
Relates to #115 & #116

fix(ui/peers): preprocess peers

---

lib/main.dart

fix(ui/peers) : make the peer list scrollable

---

android/app/build.gradle
pubspec.yaml

Update target version for android to 35
